config/routes.rb
Rails.application.routes.draw do
root 'public/homes#top'
#認証機能に関して
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }
  devise_for :customers, controllers: {
    registrations: 'publics/registrations',
    sessions: 'publics/sessions',
    passwords: 'publics/passwords'
  }


  namespace :public do
    get "/top"=> "homes#top"
    root to: 'homes#top'
    get 'homes/about' => 'homes#about'
    get 'orders/thanks' => 'orders#thanks'
  	resources :customers, only: [:index, :show, :new, :edit, :create, :update, :destroy]
      get "customers/:id/check" => "customers#check"
      patch "customers/:id/check" => "customers#withdrow"
      #退会ページのルート
    resources :items, only: [:index, :show]
    get '/orders/thanks' => 'orders#thanks'
    get '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:index, :show, :new, :confirm, :thanks, :create] do
          collection do
      post :confirm
    end
  end
    resources :deliveries, only: [:index, :edit, :update, :create, :destroy]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :create, :destroy, :update]do
      collection do
        post :next
        post :confirm
      end
    end
    resources :order_items, only: [:index]
    resources :genres, only: [:show]
  end

  namespace :admin do
  	get "/top"=> "homes#top"
    root to: 'homes#top'
  	resources :customers, only: [:index, :edit, :update, :show]
  	resources :admins, only: [:show]
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :orders, only: [:index, :show, :create, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :order_items, only: [:index, :create, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :customer
	belongs_to :item

	validates :amount, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  has_many :order

validates :last_name, presence: true
validates :first_name, presence: true
validates :last_name_kana, presence: true,
                 format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "全角カタカナのみで入力して下さい"
                 }
validates :first_name_kana, presence: true,
                 format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "全角カタカナのみで入力して下さい"
                 }

validates :postal_code, numericality: { only_integer: true }
# 郵便番号を数値だけ入力可,

validates :address, presence: true
validates :telephone_number, numericality: { only_integer: true }
# 電話番号を数値だけ入力可、



    def active_for_authentication?
        super && (self.is_deleted == false)
    end
    #is_deletedが無効の場合は有効会員(ログイン可能)


end

app/models/delivery.rb
class Delivery < ApplicationRecord
	belongs_to :customer

	validates :postal_code, presence: true
	validates :name, presence: true, length: {maximum: 10, minimum: 2}, uniqueness: true
	validates :address, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items
	validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :cart_items
    has_many :order_items
	belongs_to :genre, dependent: :destroy
	attachment :image
	validates :name, presence: true
	validates :introduction, presence: true
	validates :price, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	belongs_to :customer
	enum payment_method: {"銀行振込":0, "クレジットカード":1}


	enum status: {"入金待ち":0, "入金確認":1, "製作中":2, "発送準備中":3, "発送済":4}

		# 個数小計
	def total_count
		total = 0
		order_items.each do |order_item|
			total += order_item.amount
		end
		total
	end


   end

app/models/order_item.rb
class OrderItem < ApplicationRecord

	belongs_to :item, dependent: :destroy
	belongs_to :order,dependent: :destroy

	enum making_status: {"着手不可":0,"製作待ち":1,"製作中":2,"製作完了":3}

end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
	def index
	end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
	 before_action :authenticate_admin!

	def index
		@customers = Customer.page(params[:page]).per(8)
	end 

	def show
		@customer = Customer.find(params[:id])
	end

	def edit
		@customer = Customer.find(params[:id])
	end

	def update
		@customer = Customer.find(params[:id])
       if @customer.update(customer_params)
        flash[:notice] = "You have updated customer successfully."
        redirect_to admin_customer_path
        else
        flash[:notice] = "errors prohibited this obj from being saved:"
        render :edit
    	end
	end

	private

	def customer_params
		params.require(:customer).permit(:email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted)
	end


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
	before_action :authenticate_admin!
	def index
		@genres = Genre.all
		@genre = Genre.new
	end

	def create
		@genre = Genre.new(genre_params)
		if @genre.save
    		redirect_to admin_genres_path
    	else
		    @genres = Genre.all
		    render :index
		end
	end

	def edit
		@genre = Genre.find(params[:id])
	end

	def update
		@genre = Genre.find(params[:id])
		if @genre.update(genre_params)
			redirect_to admin_genres_path
		else
			render :edit
		end

	end

	private
	def genre_params
		params.require(:genre).permit(:name, :is_active, :sort)
	end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
	before_action :authenticate_admin!
	def top
		@genres = Genre.all
		@orders = Order.all
	end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
	before_action :authenticate_admin!

	def index
		@items = Item.page(params[:page]).per(8)
	end

	def new
		@item = Item.new
		@genres = Genre.all
	end

	def create
		@item = Item.new(item_params)
        if @item.save
         flash[:success] = "登録に成功しました"
        redirect_to admin_item_path(@item.id)
        else
          	flash[:warning] = "入力内容を確認してください"
          render :new
         end
    end

	def show
		@item = Item.find(params[:id])
		@genre = @item.genre
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		if @item.update(item_params)
			flash[:success] = "登録に成功しました"
			redirect_to admin_item_path(@item.id)
		else
			flash[:warning] = "入力内容を確認してください"
            render :edit
	     end
	 end

	private
      def item_params
        params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



	def after_sign_in_path_for(resource)
  		case resource
  			when Admin
    			admin_top_path
    		when Customer
    			public_items_path
		end
	end
	def after_sign_out_path_for(resource)
      if resource == :admin
      new_admin_session_path
      else
      new_customer_session_path
      end
    end



end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

 def price(money,rate)
   taxed_money = (money*rate).round
    "税込#{taxed_money}円"
  end
end

app/views/admin/customers/edit.html.erb
<div class="container">
	<div class="row">		
		<h2><%= @customer.last_name %><%= @customer.first_name %>の会員情報編集</h2>
	</div>
	
	<div class="row mt-3 flex-column align-items-center">		
		<%= form_for(@customer, url: admin_customer_path) do |f| %>
		
		 <div class="form-group row">
		    <%= f.label :会員id %>
		    <%= f.label @customer.id %>
		  </div>
		
		  <div class="form-group row">
		    <%= f.label :氏名 %>
		    <%= f.text_field :last_name %>
		    <%= f.text_field :first_name %>
		  </div>
		
		  <div class="form-group row">
		    <%= f.label :フリガナ%>
		    <%= f.text_field :last_name_kana %>
		    <%= f.text_field :first_name_kana %>
		  </div>
		
		  <div class="form-group row">
		    <%= f.label :郵便番号（ハイフンなし） %>
		    <%= f.text_field :postal_code %>
		  </div>
		
		  <div class="form-group row">
		    <%= f.label :住所 %>
		    <%= f.text_area :address %>
		  </div>
		
		  <div class="form-group row">
		    <%= f.label :電話番号（ハイフンなし） %>
		    <%= f.telephone_field :telephone_number %>
		  </div>
		
		  <div class="form-group row">
		    <%= f.label :メールアドレス %>
		    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
		  </div>
		
		  <div class="form-group row">
		    <%= f.label :会員ステータス %>
		    <%= f.radio_button :is_deleted, :false %>
		    <%= f.label :is_deleted, "有効会員" %>
		    <%= f.radio_button :is_deleted, :true %>
		    <%= f.label :is_deleted, "退会済み" %>
		  </div>
		
		
		  <div class="actions">
		    <%= f.submit "編集内容を保存する", class:"btn btn-primary"  %>
		  </div>
		<% end %>
	</div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
	<div class="row">
	<h2>会員一覧</h2>
	</div>
	
	<div class="row">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>会員ID</th>
					<th>氏名</th>
					<th>メールアドレス</th>
					<th>ステータス</th>
				</tr>
			</thead>
		
			<tbody>
				<% @customers.each do |customer| %>
				<tr>
					<td><%= customer.id %></td>
					<td><%= link_to admin_customer_path(customer) do %>
						<%= customer.last_name %>
		              	<%= customer.first_name %>
		              	<% end %>
					</td>
					<td><%= customer.email %></td>
					<td><% if customer.is_deleted == false %>
						有効
						<% else %>
						退会済
						<% end %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
		  <div class="row text-center">
        	<%= paginate @customers, class: "paginate" %>
  		</div>
	</div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
	<div class="row">	
		<h2><%= @customer.last_name %><%= @customer.first_name %>の会員詳細</h2>
	</div>

	<div class="row">	
		<table class="table table-borderless">
			<tr>
				<th>顧客ID</th>
				<th><%= @customer.id %></th>
				<th>
					<% if @customer.is_deleted == false %>
					<div class="bg-info d-inline text-white p-1 ml-3 rounded">
					有効会員
					</div>
					<% else %>
					<div class="bg-danger d-inline text-white p-1 ml-3 rounded">
					退会済み
					</div>
					<% end %>
				</th>
			</tr>
			<tr>
				<th>氏名</th>
				<th><%= @customer.last_name %><%= @customer.first_name %></th>
			</tr>
			<tr>
				<th>カナ</th>
				<th><%= @customer.last_name_kana %><%= @customer.first_name_kana %></th>
			</tr>
			<tr>
				<th>郵便番号</th>
				<th><%= @customer.postal_code %></th>
			</tr>
			<tr>
				<th>住所</th>
				<th><%= @customer.address %></th>
			</tr>
			<tr>
				<th>電話番号</th>
				<th><%= @customer.telephone_number %></th>
			</tr>
			<tr>
				<th>メールアドレス</th>
				<th><%= @customer.email %></th>
			</tr>
		</table>
		
		<%= link_to  edit_admin_customer_path(@customer), class:"btn btn-primary" do %>
		  <i class="fa fa-arrow-left"></i>
		  <span>編集する</span>
		<% end %>
		
		<%= link_to   admin_order_path(@customer.id), class:"btn btn-primary"  do %>
		  <i class="fa fa-arrow-left"></i>
		  <span>注文履歴一覧を見る</span>
		<% end %>
	</div>
</div>