config/routes.rb
Rails.application.routes.draw do
root 'public/homes#top'
#認証機能に関して
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }
  devise_for :customers, controllers: {
    registrations: 'publics/registrations',
    sessions: 'publics/sessions',
    passwords: 'publics/passwords'
  }


  namespace :public do
    get "/top"=> "homes#top"
    root to: 'homes#top'
    get 'homes/about' => 'homes#about'
    get 'orders/thanks' => 'orders#thanks'
  	resources :customers, only: [:index, :show, :new, :edit, :create, :update, :destroy]
      get "customers/:id/check" => "customers#check"
      patch "customers/:id/check" => "customers#withdrow"
      #退会ページのルート
    resources :items, only: [:index, :show]
    get '/orders/thanks' => 'orders#thanks'
    get '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:index, :show, :new, :confirm, :thanks, :create] do
          collection do
      post :confirm
    end
  end
    resources :deliveries, only: [:index, :edit, :update, :create, :destroy]
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :create, :destroy, :update]do
      collection do
        post :next
        post :confirm
      end
    end
    resources :order_items, only: [:index]
    resources :genres, only: [:show]
  end

  namespace :admin do
  	get "/top"=> "homes#top"
    root to: 'homes#top'
  	resources :customers, only: [:index, :edit, :update, :show]
  	resources :admins, only: [:show]
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :orders, only: [:index, :show, :create, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :order_items, only: [:index, :create, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :customer
	belongs_to :item

	validates :amount, presence: true

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :deliveries, dependent: :destroy
  has_many :order

validates :last_name, presence: true
validates :first_name, presence: true
validates :last_name_kana, presence: true,
                 format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "全角カタカナのみで入力して下さい"
                 }
validates :first_name_kana, presence: true,
                 format: {
                   with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                   message: "全角カタカナのみで入力して下さい"
                 }

validates :postal_code, numericality: { only_integer: true }
# 郵便番号を数値だけ入力可,

validates :address, presence: true
validates :telephone_number, numericality: { only_integer: true }
# 電話番号を数値だけ入力可、



    def active_for_authentication?
        super && (self.is_deleted == false)
    end
    #is_deletedが無効の場合は有効会員(ログイン可能)


end

app/models/delivery.rb
class Delivery < ApplicationRecord
	belongs_to :customer

	validates :postal_code, presence: true
	validates :name, presence: true, length: {maximum: 10, minimum: 2}, uniqueness: true
	validates :address, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items
	validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :cart_items
    has_many :order_items
	belongs_to :genre, dependent: :destroy
	attachment :image
	validates :name, presence: true
	validates :introduction, presence: true
	validates :price, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	belongs_to :customer
	enum payment_method: {"銀行振込":0, "クレジットカード":1}


	enum status: {"入金待ち":0, "入金確認":1, "製作中":2, "発送準備中":3, "発送済":4}

		# 個数小計
	def total_count
		total = 0
		order_items.each do |order_item|
			total += order_item.amount
		end
		total
	end


   end

app/models/order_item.rb
class OrderItem < ApplicationRecord

	belongs_to :item, dependent: :destroy
	belongs_to :order,dependent: :destroy

	enum making_status: {"着手不可":0,"製作待ち":1,"製作中":2,"製作完了":3}

end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController
	def index
	end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
	before_action :authenticate_admin!
	def index
		@genres = Genre.all
		@genre = Genre.new
	end

	def create
		@genre = Genre.new(genre_params)
		if @genre.save
    		redirect_to admin_genres_path
    	else
		    @genres = Genre.all
		    render :index
		end
	end

	def edit
		@genre = Genre.find(params[:id])
	end

	def update
		@genre = Genre.find(params[:id])
		if @genre.update(genre_params)
			redirect_to admin_genres_path
		else
			render :edit
		end

	end

	private
	def genre_params
		params.require(:genre).permit(:name, :is_active, :sort)
	end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
	before_action :authenticate_admin!
	def top
		@genres = Genre.all
		@orders = Order.all
	end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
	before_action :authenticate_admin!

	def index
		@items = Item.page(params[:page]).per(8)
	end

	def new
		@item = Item.new
		@genres = Genre.all
	end

	def create
		@item = Item.new(item_params)
        if @item.save
         flash[:success] = "登録に成功しました"
        redirect_to admin_item_path(@item.id)
        else
          	flash[:warning] = "入力内容を確認してください"
          render :new
         end
    end

	def show
		@item = Item.find(params[:id])
		@genre = @item.genre
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		if @item.update(item_params)
			flash[:success] = "登録に成功しました"
			redirect_to admin_item_path(@item.id)
		else
			flash[:warning] = "入力内容を確認してください"
            render :edit
	     end
	 end

	private
      def item_params
        params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
      end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	before_action :authenticate_admin!

	def index

  	  @orders = Order.page(params[:page]).per(10).order('created_at')
    end

	def show
	  @order = Order.find(params[:id])
  	  @order_items = @order.order_items
  	  @total_price = @order_items.sum{|o| o.price * o.amount}
	end

	def update
	  @order = Order.find(params[:id]) #注文詳細の特定
  	  @order_items = @order.order_items #注文から紐付く商品の取得
  	  @order.update(order_params) #注文ステータスの更新
    end


	private

	  def order_params
  	    params.require(:order).permit(:status, :making_status)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



	def after_sign_in_path_for(resource)
  		case resource
  			when Admin
    			admin_top_path
    		when Customer
    			public_items_path
		end
	end
	def after_sign_out_path_for(resource)
      if resource == :admin
      new_admin_session_path
      else
      new_customer_session_path
      end
    end



end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

 def price(money,rate)
   taxed_money = (money*rate).round
    "税込#{taxed_money}円"
  end
end

app/views/admin/genres/edit.html.erb
<h4>ジャンル編集</h4>

<div class="col-xs-5 ">

<%= form_for(@genre, url: admin_genre_path(@genre)) do |f| %>
	<div class="field row">
		<%= f.label :ジャンル %>
		<%= f.text_field :name %>
		<%= f.radio_button :is_active, true, checked: true %>
        <%= f.label :name, "有効" %>
        <%= f.radio_button :is_active, false %>
        <%= f.label :name, "無効" %>
		<%= f.submit :変更を保存する %>
	</div>
<% end %>

app/views/admin/genres/index.html.erb
<h2>ジャンル一覧・追加</h2>

<div class="col-xs-3 col-xs-offset-1">

<%= form_for(@genre, url: admin_genres_path) do |f| %>
	<div class="field row">
		<%= f.label :ジャンル %>
		<%= f.text_field :name %>
	</div>
		<%= f.radio_button :is_active, true, checked: true %>
        <%= f.label :name, "有効" %>
        <%= f.radio_button :is_active, false %>
        <%= f.label :name, "無効" %>
	<div class="actions">
	<%= f.submit :追加 %>
	</div>
<% end %>

<table>
	<thead>
		<tr>
			<th>ジャンル</th>
			<th>状態</th>
			<th></th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
	<% @genres.each do |genre| %>
		<tr>
			<td><%= genre.name %></td>
			<td>
				<% if genre.is_active == true %>
				有効
				<% else %>
				無効
				<% end %>
			</td>
			<td><%= link_to '編集する', edit_admin_genre_path(genre), class: "edit_#{genre.id}" %></td>
		</tr>
	<% end %>
	</tbody>
</table>
</div>

app/views/admin/items/edit.html.erb
<h2>商品編集ページ</h2>

  <%= form_for [:admin, @item] do |f| %>

    <%= f.attachment_field :image %>

    <h4>商品名</h4>
      <%= f.text_field :name %>

    <h4>商品説明</h4>
      <%= f.text_area :introduction %>

    <h4>税抜価格</h4>
      <%= f.text_field :price %>

      <h4>ジャンル</h4>
    <%=f.collection_select :genre_id, Genre.all, :id, :name, { prompt: '選択してください' } %>


    <h4>販売ステータス</h4>
      <%= f.select :is_active, [["販売中", "true"], ["売切中","false"]], include_blank: "選択して下さい" %>
     <%= f.submit '変更を保存する' %>

    <% end %>

app/views/admin/items/index.html.erb
<h4><strong>商品一覧</strong></h4>
<h5><%= link_to "新規登録はこちら", new_admin_item_path %></h5>
  <table class="table table-bordered" style="margin-top: 20px;">
  	<thead class = "thead-dark">
	  <tr>
	    <th>商品ID</th>
		<th>商品名</th>
		<th>税抜価格</th>
		<th>ジャンル</th>
		<th>ステータス</th>
	  </tr>
    </thead>
	  <tbody>
	  	<% @items.each do |item| %>
	    <tr>
		  <td>
			<%= item.id %>
		  </td>
		  <td>
			<%= link_to item.name, admin_item_path(item) %>
		  </td>
		  <td>
			<%= item.price %>
		  </td>
		  <td>
		  	<%= item.genre.name %>
		  </td>
          <td>
          	<%= item.is_active ? "販売中" : "売切中" %>
          </td>
      </tr>
	  </tbody>
	<% end %>
  </table>

  <div class="row text-center">
    <%= paginate @items, class: "paginate" %>
  </div>

app/views/admin/items/new.html.erb
<h3>商品新規登録</h3>
  <%= form_for [:admin, @item] do |f| %>
    <%= f.attachment_field :image %>

  <h5>商品名</h5>
    <%= f.text_field :name %>

  <h5>商品説明</h5>
    <%= f.text_area :introduction %>

  <h5>税抜価格</h5>
    <%= f.text_field :price %>円

  <h5>ジャンル</h5>
    <%=f.collection_select :genre_id, @genres, :id, :name, { prompt: '選択してください' } %>

  <h5>販売ステータス</h5>
    <%= f.select :is_active, [["販売中", "true"], ["売切中","false"]], include_blank: "選択して下さい" %>

     <%= f.submit '新規登録',class: "btn-sm btn-primary edit_book_#{@item.id}" %>
    <% end %>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8">
      <div class="col-lg-10 space">
        <div class="container">
          <div class="row">
            <h2>商品詳細画面</h2>
          <div class="col-lg-4 offset-lg-2">
              <%= attachment_image_tag(@item, :image, :fill, 360, 300, fallback: "no-image-mini.jpg") %>
          </div>
          <div class="col-lg-4">
            <table>
	          <tr><th><h4>商品名</h4></th><td><%= @item.name %></td></tr>
	          <tr><th><h4>商品説明</h4></th><td><%= @item.introduction %></td></tr>
	          <tr><th><h4>ジャンル</h4></th><td><%= @genre.name %></td></tr>
	          <tr><th><h4>税込価格 (税抜価格)</h4></th><td><%= (@item.price*1.1).floor %> (<%= @item.price %>)円</td></tr>
              <tr><th><h4>販売ステータス</h4></th>
                <td><% if @item.is_active == true %>
      	              <%= "販売中" %>
    	            <% else %>
    	              <%= "売切中" %>
    	            <% end %>
    	        </td></tr>
            </table>

          <div>
　          <%= link_to "編集する", edit_admin_item_path(@item), class: "btn-sm btn-success edit_book_#{@item.id}"%>
          </div>

app/views/admin/orders/index.html.erb
<div class="container takasa">
  <h2>注文履歴一覧</h2><br>
	<table class="table table-hover">
	  <tr class="active">
      <th>購入日時</th>
      <th>購入者</th>
      <th>個数</th>
      <th>注文ステータス</th>
      <th></th>
    </tr>
    <% @orders.each do |order| %>
    <tr>
      <td>
      	<%= order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
      <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
      <td><%= order.total_count %></td>
      <td><%= order.status %></td>
      <td><%= link_to "注文詳細", admin_order_path(order), class:"btn btn-primary" %></td>
    </tr>
    <% end %>
  </table>

  <div class="row text-center">
    <%= paginate @orders, class: "paginate" %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container takasa">
  <div class="row">
    <div class="col-xs-12">
      <h2>注文履歴詳細</h2>
      <!-- 購入詳細情報 -->
      <table>
       <tr>
        <th class= "order-show">購入者</th>
        <td><%= @order.customer.last_name %> <%= @order.customer.first_name %></td>

      </tr>
      <tr>
        <th class= "order-show">配送先</th>
        <td>〒<%= @order.postal_code %> <%= @order.address %><br><%= @order.name %></td>
      </tr>
      <tr>
        <th class= "order-show">支払い方法</th>
        <td><%= @order.payment_method %></td>
      </tr>
      <tr>

        <!-- 注文ステータス変更　プルダウン　更新を押すとアップデート -->
        <th>注文ステータス</th>
        <td>
          <%= form_for @order, url: admin_order_path do |f| %><!--oreder controllerのupdateの飛ぶ-->
          　<%= f.select :status,["入金待ち","入金確認","製作中","発送準備中","発送済"] ,style: "margin-top:10px;#" %><!--ステータス選択 -->
          <%= f.submit "更新" ,class: "btn btn-primary btn-sm" %></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
  <div class="orders-show">
    <div class=" col-xs-9">
      <table class="table ">
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
          <th></th>
        </tr>
        <%  @order_items.each do |order_item| %><!--注文した商品の履歴一覧をeach分で表示　-->
        <tr>
          <td><%= order_item.item.name %></td>
          <td><%= order_item.price %></td>
          <td><%= order_item.amount %></td>
          <td><%= ((order_item.price)*(order_item.amount)) %> </td>
        <!-- 製作ステータス変更　更新を押すと更新-->
          <%= form_for order_item,url: admin_order_item_path(order_item) do |f| %>
          <td><%= f.select :making_status,["着手不可","製作待ち","製作中","製作完了"] %></td><!--ステータス選択 -->
          <td><%= f.submit "更新" ,class:"btn btn-primary btn-xs" %></td>
          <% end %>
        </tr>
          <% end %>
      </table>
    </div>


    <div class="total">
     <h4>商品合計     <%= @total_price %>円</h4>
     <h4>送料　　　    <%= 800 %>円</h4>
     <h4>請求金額合計　<%=@total_price + 800 %>円</h4>
    </div>
  </div>